url: "https://jbshub765.github.io"
baseurl: "/soundproof-bedroom-site"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: "JBInsights"
description: "Practical buying advice and how-to guides in acoustics, ergonomics, smart-home, and travel gadgets."
author: JBInsights Editorial
markdown: kramdown
defaults:
  - scope: {path: ""}
    values:
      layout: default
google_analytics: G-87WW4V1T7L
plausible_domain: "jbshub765.github.io"
