- name: NICETOWN Noise Reducing Blackout Curtains
  category: acoustics
  asin: B01CS31NDE
  url: "https://www.amazon.com/dp/B01CS31NDE?tag=jbinsights-21"
  notes: Bedroom blackout curtains; multiple sizes/colours.
  alternates:
    - "https://www.amazon.com/s?k=blackout+curtains+noise+reducing&tag=jbinsights-21"

- name: Ekkogo Acoustic Panels 12-Pack
  category: acoustics
  asin: B0BKVS2614
  url: "https://www.amazon.com/dp/B0BKVS2614?tag=jbinsights-21"
  notes: Foam panels for echo control and basic isolation.
  alternates:
    - "https://www.amazon.com/s?k=acoustic+panels+12+pack&tag=jbinsights-21"

- name: TMS Mass Loaded Vinyl 1lb 4'x25'
  category: acoustics
  asin: B008JHE1P6
  url: "https://www.amazon.com/dp/B008JHE1P6?tag=jbinsights-21"
  notes: Dense barrier for walls, doors and floors.
  alternates:
    - "https://www.amazon.com/s?k=mass+loaded+vinyl+1lb&tag=jbinsights-21"

- name: Holikme Door Draft Stopper (2\" x 39\")
  category: acoustics
  asin: B072QDSJKT
  url: "https://www.amazon.com/dp/B072QDSJKT?tag=jbinsights-21"
  notes: Seal under-door gap; choose colour to match decor.
  alternates:
    - "https://www.amazon.com/s?k=door+draft+stopper&tag=jbinsights-21"

- name: 3M Indoor Window Insulator Kit
  category: acoustics
  asin: B00002NCJI
  url: "https://www.amazon.com/dp/B00002NCJI?tag=jbinsights-21"
  notes: Seasonal window film kit; reduces drafts and noise.
  alternates:
    - "https://www.amazon.com/s?k=3M+window+insulator+kit&tag=jbinsights-21"

- name: Hbada Reclining Ergonomic Office Chair
  category: ergonomics
  asin: B07X54D9KX
  url: "https://www.amazon.com/dp/B07X54D9KX?tag=jbinsights-21"
  notes: Reclining mesh chair with leg rest.
  alternates:
    - "https://www.amazon.com/s?k=ergonomic+office+chair+reclining&tag=jbinsights-21"

- name: Blink Outdoor 4 Security Camera (Single Cam)
  category: smart-home
  asin: B0CNZDGTBM
  url: "https://www.amazon.com/dp/B0CNZDGTBM?tag=jbinsights-21"
  notes: Budget-friendly outdoor cam; verify latest ASIN.
  alternates:
    - "https://www.amazon.com/s?k=Blink+Outdoor+4&tag=jbinsights-21"

- name: WYZE Cam v3 (Alt pick)
  category: smart-home
  asin: B08R5QD1G6
  url: "https://www.amazon.com/dp/B08R5QD1G6?tag=jbinsights-21"
  notes: 1080p wired indoor/outdoor; low price.
  alternates:
    - "https://www.amazon.com/s?k=Wyze+Cam+v3&tag=jbinsights-21"

- name: Anker PowerCore 10000
  category: travel
  asin: B0194WDVHI
  url: "https://www.amazon.com/dp/B0194WDVHI?tag=jbinsights-21"
  notes: Compact 10k mAh; perennial bestseller.
  alternates:
    - "https://www.amazon.com/s?k=Anker+PowerCore+10000&tag=jbinsights-21"
