name: Plausible Metrics
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Fetch Plausible metrics
        env:
          PLAUSIBLE_API_KEY: ${{ secrets.PLAUSIBLE_API_KEY }}
          PLAUSIBLE_SITE_ID: ${{ secrets.PLAUSIBLE_SITE_ID }}
        run: python -u scripts/fetch_plausible.py
      - name: Commit report
        run: |
          git config user.name "jbinsights-bot"
          git config user.email "actions@users.noreply.github.com"
          git add _reports/ || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(analytics): update Plausible report"
            git push
          fi
